# Generated by Django 5.0.1 on 2024-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='full name'),
        ),
    ]
