# Generated by Django 5.0.1 on 2024-02-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_submission_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='country',
            new_name='countries',
        ),
    ]
