# Generated by Django 5.0.1 on 2024-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_rename_country_submission_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='age_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='age group'),
        ),
    ]
