# Generated by Django 5.0.1 on 2024-02-12 11:55

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_submission_age_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='English name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='English name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.dishcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='English name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ingredients', models.ManyToManyField(blank=True, to='survey.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='English name')),
                ('local_name', models.CharField(blank=True, max_length=50, verbose_name='Local name')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Role of dish')),
                ('time_of_day', models.CharField(blank=True, max_length=50, verbose_name='Time of day')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('regions', models.CharField(blank=True, max_length=200, verbose_name='Regions')),
                ('image', models.ImageField(blank=True, upload_to='dishes/', verbose_name='image')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.dishcategory')),
                ('ingredients', models.ManyToManyField(blank=True, to='survey.ingredient')),
                ('variations', models.ManyToManyField(blank=True, to='survey.variations')),
            ],
        ),
    ]
