# Generated by Django 5.0.1 on 2024-02-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_rename_variations_variation_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='local_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Local name'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.dishcategory'),
        ),
    ]
