# Generated by Django 5.0.1 on 2024-03-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_variation_local_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='has_consent',
        ),
    ]
