# Generated by Django 5.0.1 on 2024-03-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_submission_year_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='age_group',
        ),
    ]
