# Generated by Django 5.0.1 on 2024-03-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_remove_submission_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('official_name', models.CharField(max_length=50, verbose_name='Official name')),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Oceania', 'Oceania'), ('South America', 'South America')], max_length=50, verbose_name='Continent')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.RemoveField(
            model_name='submission',
            name='countries',
        ),
        migrations.AddField(
            model_name='submission',
            name='countries',
            field=models.ManyToManyField(blank=True, to='survey.country'),
        ),
    ]
