# Generated by Django 5.0.1 on 2024-03-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_country_remove_submission_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.AddField(
            model_name='country',
            name='association',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Association'),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Official name'),
        ),
    ]
