# Generated by Django 5.0.1 on 2024-03-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_remove_country_continent_country_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='national_identity',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe your national identity'),
        ),
    ]
