# Generated by Django 5.0.1 on 2024-03-06 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_submission_national_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='country',
        ),
        migrations.AddField(
            model_name='dish',
            name='countries',
            field=models.ManyToManyField(blank=True, to='survey.country'),
        ),
        migrations.AddField(
            model_name='dish',
            name='countries_more',
            field=models.CharField(blank=True, max_length=200, verbose_name="If we weren't able to capture all the countries you’d expect in this list, please add more below! (optional)"),
        ),
        migrations.AddField(
            model_name='dish',
            name='cultures',
            field=models.CharField(blank=True, max_length=200, verbose_name='Is this dish attributed to a specific cultural, social, or ethnic group? If you know, could you list these below? '),
        ),
        migrations.AddField(
            model_name='dish',
            name='language',
            field=models.CharField(default='English', max_length=50, verbose_name='What is the name of the local language?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dish',
            name='local_name',
            field=models.CharField(max_length=50, verbose_name='What is the name of the dish in the local language?'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, verbose_name='What is the name of the dish in English?'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='regions',
            field=models.CharField(blank=True, max_length=200, verbose_name='What region in that country does the dish come from, if you know?'),
        ),
    ]
