# Generated by Django 5.0.1 on 2024-03-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_remove_dish_category_remove_dish_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='variations',
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Can you briefly describe the dish?'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='time_of_day',
            field=models.CharField(blank=True, max_length=255, verbose_name='Time of day'),
        ),
        migrations.DeleteModel(
            name='DishCategory',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
