# Generated by Django 5.0.1 on 2024-03-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_remove_variation_ingredients_remove_dish_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='role',
        ),
        migrations.AddField(
            model_name='dish',
            name='type_of_dish',
            field=models.CharField(blank=True, max_length=255, verbose_name='Type of dish'),
        ),
    ]
