# Generated by Django 5.0.1 on 2024-03-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_remove_dish_role_dish_type_of_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='drink',
            field=models.CharField(blank=True, max_length=200, verbose_name='Is it typically accompanied by a drink? What kind?'),
        ),
        migrations.AddField(
            model_name='dish',
            name='occasions',
            field=models.CharField(default='regular', max_length=200, verbose_name='Is this dish eaten regularly, only on special occasions, or both?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='occasions_more',
            field=models.CharField(blank=True, max_length=200, verbose_name='If eaten on special occasions, what kind?'),
        ),
        migrations.AddField(
            model_name='dish',
            name='time_of_day_more',
            field=models.CharField(blank=True, help_text='Please feel free to add any more information (optional)', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='dish',
            name='type_of_dish_more',
            field=models.CharField(blank=True, help_text='Please feel free to add any more information (optional)', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='dish',
            name='utensils',
            field=models.CharField(blank=True, help_text='For example, fork and knife; right hand; chopsticks', max_length=200, verbose_name='What utensils are used to eat this dish? '),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Can you briefly describe the dish?'),
        ),
    ]
