# Generated by Django 5.0.1 on 2024-03-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_dish_drink_dish_occasions_dish_occasions_more_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='association',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Association'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Official name'),
        ),
    ]
