# Generated by Django 5.0.1 on 2024-03-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_alter_country_association_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Country code'),
        ),
    ]
