# Generated by Django 5.0.1 on 2024-03-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_remove_ingredient_description_alter_dish_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, help_text='If you have multiple URLs, please provide them in a new line.', max_length=400, verbose_name='Do you know of any online recipes for this? If so, please provide the URL. '),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishes/', verbose_name='Photo of food'),
        ),
    ]
