# Generated by Django 5.0.1 on 2024-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_remove_dish_description_dish_recipe_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='more_details',
            field=models.TextField(blank=True, help_text='Tell us what the dish looks like or tastes like, its cultural importance, or whatever else!', max_length=600, verbose_name='Anything we’ve missed about the dish that you want to tell us?'),
        ),
    ]
