# Generated by Django 5.0.1 on 2024-03-09 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0025_dish_more_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dish",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
