# Generated by Django 5.0.1 on 2024-03-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0026_dish_created_at_dish_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
