# Generated by Django 5.0.1 on 2024-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_alter_dish_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients_more',
            field=models.CharField(blank=True, help_text='Please feel free to add any ingredients that are missing from the above (optional)', max_length=200, verbose_name=''),
        ),
    ]
