# Generated by Django 5.0.1 on 2024-03-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0028_dishrating"),
        ("survey", "0029_dish_ingredients_more"),
    ]

    operations = []
