# Generated by Django 5.0.1 on 2024-03-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_merge_0028_dishrating_0029_dish_ingredients_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(help_text="If there isn't an English word for it, please write a phonetic approximation of how it is pronounced.", max_length=200, verbose_name='What is the name of the dish in English?'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='regions',
            field=models.TextField(blank=True, help_text='If there are multiple, please enter each region in a new line.', max_length=500, verbose_name='What region in that country does the dish come from, if you know?'),
        ),
    ]
