# Generated by Django 5.0.1 on 2024-03-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_alter_dish_name_alter_dish_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='regions',
            field=models.TextField(blank=True, help_text="Please enter each region in a new line. If you've selected multiple countries, please also indicate the corresponding country in brackets.", max_length=500, verbose_name='Which regions in that country / countries does the dish come from, if you know?'),
        ),
    ]
