# Generated by Django 5.0.1 on 2024-03-22 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0035_remove_dish_name_dish_english_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishrating",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.dish"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dishrating",
            unique_together={("created_by", "dish")},
        ),
    ]
