# Generated by Django 5.0.1 on 2024-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_alter_dishrating_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='survey.ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='utensils',
            field=models.CharField(blank=True, help_text='For example, spoon; knife and fork; fingers; right hand; left hand; chopsticks', max_length=200, verbose_name='What utensils are used to eat this dish? '),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text="Please enter a name in singular form where possible. If there isn't a name for the ingredient in English, please feel free to add this in the local language. Once this step is done, please re-enter this ingredient in the box on the main website.", max_length=200, unique=True, verbose_name='name'),
        ),
    ]
