# Generated by Django 5.0.1 on 2024-03-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_alter_dish_english_name_alter_dish_more_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_details',
            field=models.TextField(blank=True, max_length=600, verbose_name='Image details'),
        ),
    ]
