# Generated by Django 5.0.1 on 2024-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0039_dish_image_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="If you have multiple URLs, please provide them in a new line.",
                null=True,
                verbose_name="If you were unable to upload a personal photo of this dish, could you share a link or URL to an online image that you think captures this dish well?",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="English name"
            ),
        ),
    ]
