# Generated by Django 5.0.1 on 2024-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0040_dish_image_url_alter_dish_english_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image_url",
            field=models.URLField(
                blank=True,
                null=True,
                verbose_name="If you were unable to upload a personal photo of this dish, could you share a link or URL to an online image that you think captures this dish well?",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="regions",
            field=models.TextField(
                blank=True,
                help_text="If you've selected multiple countries, please also indicate the corresponding country in brackets for each region.",
                max_length=500,
                verbose_name="Which regions in that country / countries does the dish come from, if you know?",
            ),
        ),
    ]
