# Generated by Django 5.0.1 on 2024-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_alter_dish_image_url_alter_dish_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='over_aged',
            field=models.BooleanField(null=True, verbose_name='I confirm that I am or over 18 years old'),
        ),
    ]
