# Generated by Django 5.0.1 on 2024-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0042_submission_over_aged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="Image URL"),
        ),
    ]
