# Generated by Django 5.0.1 on 2024-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_consent',
            field=models.BooleanField(default=False, verbose_name='consent'),
        ),
    ]
