# Generated by Django 5.0.1 on 2024-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_middle_name_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='acknowledgement',
            field=models.BooleanField(default=True, verbose_name='acknowledgement'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_consent',
            field=models.BooleanField(default=True, verbose_name='consent'),
        ),
    ]
