# Generated by Django 5.0.1 on 2024-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_acknowledgement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='has_consent',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='full name'),
        ),
    ]
