# Generated by Django 5.0.1 on 2024-03-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acknowledgement',
            field=models.BooleanField(default=True, verbose_name='acknowledgement'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followup_consent',
            field=models.BooleanField(default=True, verbose_name='followup_consent'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=50, verbose_name='full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='future_contact',
            field=models.BooleanField(default=True, verbose_name='future_contact'),
        ),
    ]
